name: APIのリポジトリの GraphQL Schema IDL を読んで TypeScript の型を生成し、PRを作成する
on:
  repository_dispatch:
    types: [ repository-dispatch-test ]
jobs:
  repository-dispatch-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: README.mdを更新
        run: echo "awesome_eventsレポジトリからイベントを受け取りました。" >> README.md
      - name: PR作成
        # uses: peter-evans/create-pull-request@v3
        # with:
        #   token: ${{ secrets.PAT }}
        #   base: test_root
        #   branch: test_pr_branch
        #   title: '[bot]awesome_eventsのREADME.mdが更新されたのでPR作成'
        run: gh pr create -B "feature/project_root" -t "[bot]PR" -b ""
        env:
          GH_TOKEN: ${{ secrets.PAT }}
